using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Acknex3.Api
{
    public static class Events
    {
        /* Events */
        public static Func<IEnumerator> If_0;
        public static Func<IEnumerator> If_1;
        public static Func<IEnumerator> If_2;
        public static Func<IEnumerator> If_3;
        public static Func<IEnumerator> If_4;
        public static Func<IEnumerator> If_5;
        public static Func<IEnumerator> If_6;
        public static Func<IEnumerator> If_7;
        public static Func<IEnumerator> If_8;
        public static Func<IEnumerator> If_9;
        public static Func<IEnumerator> If_a;
        public static Func<IEnumerator> If_alt;
        public static Func<IEnumerator> If_anykey;
        public static Func<IEnumerator> If_apo;
        public static Func<IEnumerator> If_b;
        public static Func<IEnumerator> If_bksl;
        public static Func<IEnumerator> If_bksp;
        public static Func<IEnumerator> If_brackl;
        public static Func<IEnumerator> If_brackr;
        public static Func<IEnumerator> If_c;
        public static Func<IEnumerator> If_cal;
        public static Func<IEnumerator> If_car;
        public static Func<IEnumerator> If_comma;
        public static Func<IEnumerator> If_ctrl;
        public static Func<IEnumerator> If_cud;
        public static Func<IEnumerator> If_cul;
        public static Func<IEnumerator> If_cur;
        public static Func<IEnumerator> If_cuu;
        public static Func<IEnumerator> If_d;
        public static Func<IEnumerator> If_del;
        public static Func<IEnumerator> If_e;
        public static Func<IEnumerator> If_end;
        public static Func<IEnumerator> If_enter;
        public static Func<IEnumerator> If_equals;
        public static Func<IEnumerator> If_esc;
        public static Func<IEnumerator> If_f;
        public static Func<IEnumerator> If_f1;
        public static Func<IEnumerator> If_f10;
        public static Func<IEnumerator> If_f11;
        public static Func<IEnumerator> If_f12;
        public static Func<IEnumerator> If_f2;
        public static Func<IEnumerator> If_f3;
        public static Func<IEnumerator> If_f4;
        public static Func<IEnumerator> If_f5;
        public static Func<IEnumerator> If_f6;
        public static Func<IEnumerator> If_f7;
        public static Func<IEnumerator> If_f8;
        public static Func<IEnumerator> If_f9;
        public static Func<IEnumerator> If_g;
        public static Func<IEnumerator> If_h;
        public static Func<IEnumerator> If_hit;
        public static Func<IEnumerator> If_home;
        public static Func<IEnumerator> If_i;
        public static Func<IEnumerator> If_ins;
        public static Func<IEnumerator> If_j;
        public static Func<IEnumerator> If_k;
        public static Func<IEnumerator> If_klick;
        public static Func<IEnumerator> If_l;
        public static Func<IEnumerator> If_left;
        public static Func<IEnumerator> If_load;
        public static Func<IEnumerator> If_m;
        public static Func<IEnumerator> If_middle;
        public static Func<IEnumerator> If_minus;
        public static Func<IEnumerator> If_mstop;
        public static Func<IEnumerator> If_n;
        public static Func<IEnumerator> If_o;
        public static Func<IEnumerator> If_p;
        public static Func<IEnumerator> If_pause;
        public static Func<IEnumerator> If_period;
        public static Func<IEnumerator> If_pgdn;
        public static Func<IEnumerator> If_pgup;
        public static Func<IEnumerator> If_plus;
        public static Func<IEnumerator> If_q;
        public static Func<IEnumerator> If_r;
        public static Func<IEnumerator> If_right;
        public static Func<IEnumerator> If_s;
        public static Func<IEnumerator> If_semic;
        public static Func<IEnumerator> If_slash;
        public static Func<IEnumerator> If_space;
        public static Func<IEnumerator> If_start;
        public static Func<IEnumerator> If_sz;
        public static Func<IEnumerator> If_t;
        public static Func<IEnumerator> If_tab;
        public static Func<IEnumerator> If_u;
        public static Func<IEnumerator> If_v;
        public static Func<IEnumerator> If_w;
        public static Func<IEnumerator> If_x;
        public static Func<IEnumerator> If_y;
        public static Func<IEnumerator> If_z;
    }
}
