using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Acknex3.Api
{
    public static class Events
    {
        /* Events */
        public static Function If_0;
        public static Function If_1;
        public static Function If_2;
        public static Function If_3;
        public static Function If_4;
        public static Function If_5;
        public static Function If_6;
        public static Function If_7;
        public static Function If_8;
        public static Function If_9;
        public static Function If_a;
        public static Function If_alt;
        public static Function If_anykey;
        public static Function If_apo;
        public static Function If_b;
        public static Function If_bksl;
        public static Function If_bksp;
        public static Function If_brackl;
        public static Function If_brackr;
        public static Function If_c;
        public static Function If_cal;
        public static Function If_car;
        public static Function If_comma;
        public static Function If_ctrl;
        public static Function If_cud;
        public static Function If_cul;
        public static Function If_cur;
        public static Function If_cuu;
        public static Function If_d;
        public static Function If_del;
        public static Function If_e;
        public static Function If_end;
        public static Function If_enter;
        public static Function If_equals;
        public static Function If_esc;
        public static Function If_f;
        public static Function If_f1;
        public static Function If_f10;
        public static Function If_f11;
        public static Function If_f12;
        public static Function If_f2;
        public static Function If_f3;
        public static Function If_f4;
        public static Function If_f5;
        public static Function If_f6;
        public static Function If_f7;
        public static Function If_f8;
        public static Function If_f9;
        public static Function If_g;
        public static Function If_h;
        public static Function If_hit;
        public static Function If_home;
        public static Function If_i;
        public static Function If_ins;
        public static Function If_j;
        public static Function If_joy4;
        public static Function If_k;
        public static Function If_klick;
        public static Function If_l;
        public static Function If_left;
        public static Function If_load;
        public static Function If_m;
        public static Function If_middle;
        public static Function If_minus;
        public static Function If_mstop;
        public static Function If_n;
        public static Function If_o;
        public static Function If_p;
        public static Function If_pause;
        public static Function If_period;
        public static Function If_pgdn;
        public static Function If_pgup;
        public static Function If_plus;
        public static Function If_q;
        public static Function If_r;
        public static Function If_right;
        public static Function If_s;
        public static Function If_semic;
        public static Function If_slash;
        public static Function If_space;
        public static Function If_start;
        public static Function If_sz;
        public static Function If_t;
        public static Function If_tast;
        public static Function If_tab;
        public static Function If_u;
        public static Function If_v;
        public static Function If_w;
        public static Function If_x;
        public static Function If_y;
        public static Function If_z;
    }
}
